name: Deploy

on:
  workflow_dispatch:
    inputs:
      page:
        description: "Pages"
        required: true
        type: string

      token:
        description: "Token"
        required: true
        type: string
        
      account:
        description: "Account"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Pages Functions
        uses: cloudflare/pages-action@v1
        with:
          projectName: ${{ inputs.page }}
          accountId: ${{ inputs.account }}
          apiToken: ${{ inputs.token }}
          branch: main
          directory: .
